"use client";

import Link from "next/link";
import { ArrowLeft, Download, ExternalLink, Printer } from "lucide-react";
import { useEffect, useState } from "react";
import { downloadBillOfLadingPdf, getBillOfLading, type BillOfLading } from "@/lib/api/bill-of-lading";

export default function BillOfLadingPreviewPage({ params }: { params: { id: string } }) {
  const [document, setDocument] = useState<BillOfLading | null>(null);
  const [pdfUrl, setPdfUrl] = useState<string | null>(null);
  const [error, setError] = useState<string | null>(null);

  useEffect(() => {
    let objectUrl: string | null = null;
    let active = true;

    void (async () => {
      try {
        const item = await getBillOfLading(params.id);
        if (!active) return;
        setDocument(item);

        if (!["ISSUED", "RELEASED", "SURRENDERED"].includes(item.status)) {
          throw new Error("Only issued, released, or surrendered Bills of Lading have a final PDF preview.");
        }

        const blob = await downloadBillOfLadingPdf(item.id);
        if (!active) return;
        objectUrl = URL.createObjectURL(blob);
        setPdfUrl(objectUrl);
      } catch (reason: unknown) {
        if (active) setError(reason instanceof Error ? reason.message : "Unable to load PDF preview");
      }
    })();

    return () => {
      active = false;
      if (objectUrl) URL.revokeObjectURL(objectUrl);
    };
  }, [params.id]);

  return (
    <main className="min-h-screen bg-[#0a0a0a] px-6 py-6 text-white">
      <div className="mx-auto max-w-7xl">
        <div className="mb-5 flex flex-wrap items-center justify-between gap-3">
          <Link href={`/bills-of-lading/${params.id}`} className="inline-flex items-center gap-2 text-sm text-zinc-500 hover:text-white">
            <ArrowLeft size={15} /> Back to B/L
          </Link>

          {pdfUrl && document && (
            <div className="flex gap-2">
              <button
                onClick={() => window.open(pdfUrl, "_blank", "noopener,noreferrer")}
                className="inline-flex items-center gap-2 rounded-lg border border-zinc-700 px-4 py-2 text-sm hover:bg-zinc-900"
              >
                <ExternalLink size={15} /> Open PDF
              </button>
              <a
                href={pdfUrl}
                download={`${document.blNumber}-v${document.version}.pdf`}
                className="inline-flex items-center gap-2 rounded-lg bg-white px-4 py-2 text-sm font-semibold text-black"
              >
                <Download size={15} /> Download
              </a>
              <button
                onClick={() => {
                  const frame = window.document.getElementById("bl-pdf-frame") as HTMLIFrameElement | null;
                  frame?.contentWindow?.print();
                }}
                className="inline-flex items-center gap-2 rounded-lg border border-zinc-700 px-4 py-2 text-sm hover:bg-zinc-900"
              >
                <Printer size={15} /> Print
              </button>
            </div>
          )}
        </div>

        <div className="mb-4">
          <h1 className="text-2xl font-semibold">{document?.blNumber ?? "Bill of Lading"} PDF Preview</h1>
          <p className="mt-1 text-sm text-zinc-500">Final controlled document preview. The PDF shown here is generated by the same document engine used for issuance.</p>
        </div>

        {error ? (
          <div className="rounded-xl border border-red-900 bg-red-950/20 p-5 text-sm text-red-300">{error}</div>
        ) : pdfUrl ? (
          <div className="overflow-hidden rounded-xl border border-zinc-800 bg-zinc-900 shadow-2xl">
            <iframe id="bl-pdf-frame" title="Bill of Lading PDF" src={pdfUrl} className="h-[calc(100vh-180px)] min-h-[720px] w-full bg-white" />
          </div>
        ) : (
          <div className="flex min-h-[500px] items-center justify-center rounded-xl border border-zinc-800 bg-zinc-950 text-sm text-zinc-500">Loading PDF preview...</div>
        )}
      </div>
    </main>
  );
}
