"use client";

import { useEffect, useState } from "react";
import { useRouter, useSearchParams } from "next/navigation";
import { z } from "zod";
import { createBillOfLading } from "@/lib/api/bill-of-lading";
import { getBookingByNumber, type BookingReference } from "@/lib/api/bookings";

const schema = z.object({
  bookingNumber:z.string().regex(/^[1-9]\d{9}$/),
  carrierName:z.string().min(2), carrierAddress:z.string().optional(),
  shipperName:z.string().min(2), shipperAddress:z.string().min(2),
  consigneeName:z.string().min(2), consigneeAddress:z.string().min(2),
  notifyPartyName:z.string().optional(), notifyPartyAddress:z.string().optional(),
  placeOfReceipt:z.string().optional(), portOfLoading:z.string().min(2), portOfDischarge:z.string().min(2), placeOfDelivery:z.string().optional(),
  vesselName:z.string().optional(), voyageNumber:z.string().optional(), placeOfIssue:z.string().min(2),
  numberOfOriginals:z.coerce.number().int().min(1).max(9), description:z.string().min(2), marksAndNumbers:z.string().optional(),
  totalPackages:z.coerce.number().int().nonnegative().optional(), totalGrossWeight:z.coerce.number().nonnegative().optional(), totalMeasurement:z.coerce.number().nonnegative().optional(),
  currency:z.string().length(3).optional(), declaredValue:z.coerce.number().nonnegative().optional(), freightTerms:z.string().optional(), termsText:z.string().optional()
});
type State=z.infer<typeof schema>;
const initial:State={bookingNumber:"",carrierName:"ZENU",carrierAddress:"",shipperName:"",shipperAddress:"",consigneeName:"",consigneeAddress:"",notifyPartyName:"",notifyPartyAddress:"",placeOfReceipt:"",portOfLoading:"",portOfDischarge:"",placeOfDelivery:"",vesselName:"",voyageNumber:"",placeOfIssue:"Djibouti",numberOfOriginals:3,description:"",marksAndNumbers:"",currency:"USD",freightTerms:"PREPAID",termsText:""};

export function BillOfLadingCreateForm(){
  const router=useRouter(); const searchParams=useSearchParams(); const [form,setForm]=useState(initial); const [bookingNumber,setBookingNumber]=useState(""); const [booking,setBooking]=useState<BookingReference|null>(null); const [lookingUp,setLookingUp]=useState(false); const [error,setError]=useState<string|null>(null); const [saving,setSaving]=useState(false);
  useEffect(()=>{const value=searchParams.get("bookingNumber");if(value){setBookingNumber(value);void (async()=>{try{setLookingUp(true);const b=await getBookingByNumber(value);setBooking(b);setForm(v=>({...v,bookingNumber:b.bookingNumber,placeOfReceipt:b.origin,portOfLoading:b.origin,portOfDischarge:b.destination,description:b.cargoDescription,totalGrossWeight:b.weight,totalMeasurement:b.volume??undefined}));}catch(e:unknown){setError(e instanceof Error?e.message:"Booking not found");}finally{setLookingUp(false);}})();}},[searchParams]);
  const update=(key:keyof State,value:string)=>setForm(v=>({...v,[key]:value}));
  async function lookup(){const value=bookingNumber.trim();if(!/^\d{10}$/.test(value)){setError("Enter the 10-digit booking number.");return;}setLookingUp(true);setError(null);try{const b=await getBookingByNumber(value);setBooking(b);setForm(v=>({...v,bookingNumber:b.bookingNumber,placeOfReceipt:b.origin,portOfLoading:b.origin,portOfDischarge:b.destination,description:b.cargoDescription,totalGrossWeight:b.weight,totalMeasurement:b.volume??undefined}));}catch(e:unknown){setBooking(null);setError(e instanceof Error?e.message:"Booking not found");}finally{setLookingUp(false);}}
  async function submit(e:React.FormEvent<HTMLFormElement>){e.preventDefault();setError(null);const parsed=schema.safeParse(form);if(!parsed.success){setError(parsed.error.issues.map(i=>i.message).join("; "));return;}if(!booking){setError("Lookup a valid booking before creating the B/L.");return;}try{setSaving(true);const doc=await createBillOfLading(parsed.data);router.push(`/bills-of-lading/${doc.id}`);}catch(e:unknown){setError(e instanceof Error?e.message:"Unable to create B/L");}finally{setSaving(false);}}
  const input="mt-2 w-full rounded-lg border border-zinc-800 bg-zinc-950 px-3 py-2.5 text-sm text-white outline-none focus:border-zinc-500";
  return <form onSubmit={submit} className="space-y-8">
    {error&&<div className="rounded-xl border border-red-900 bg-red-950/30 p-4 text-sm text-red-300">{error}</div>}
    <section className="rounded-xl border border-zinc-800 bg-zinc-950 p-6"><h2 className="text-lg font-semibold">Booking Reference</h2><p className="mt-1 text-sm text-zinc-500">The booking number is the source of truth. The B/L number will be inherited as ZENU + booking number.</p><div className="mt-5 flex gap-3"><input inputMode="numeric" maxLength={10} value={bookingNumber} onChange={e=>setBookingNumber(e.target.value.replace(/\D/g,""))} placeholder="10-digit booking number" className={input}/><button type="button" onClick={()=>void lookup()} disabled={lookingUp} className="rounded-lg bg-white px-5 text-sm font-semibold text-black disabled:opacity-50">{lookingUp?"Looking up...":"Lookup"}</button></div>{booking&&<div className="mt-5 rounded-lg border border-emerald-900 bg-emerald-950/20 p-4"><div className="font-mono text-xl font-bold">ZENU{booking.bookingNumber}</div><div className="mt-1 text-sm text-zinc-400">{booking.origin} → {booking.destination} · {booking.status}</div></div>}</section>
    <section className="rounded-xl border border-zinc-800 bg-zinc-950 p-6"><h2 className="text-lg font-semibold">Customer & Carrier</h2><p className="mt-1 text-sm text-zinc-500">Customer identity is inherited from the booking and cannot be changed at B/L creation.</p><div className="mt-5 grid gap-5 md:grid-cols-2"><div><span className="text-xs uppercase text-zinc-500">Customer</span><div className="mt-2 rounded-lg border border-zinc-800 bg-black px-3 py-2.5 text-sm text-zinc-300">{booking?.customer?.name ?? "Lookup a booking"}</div></div><Field label="Carrier Name" value={form.carrierName} onChange={v=>update("carrierName",v)}/><Field label="Carrier Address" value={form.carrierAddress} onChange={v=>update("carrierAddress",v)} multiline/></div></section>
    <section className="rounded-xl border border-zinc-800 bg-zinc-950 p-6"><h2 className="text-lg font-semibold">Parties</h2><div className="mt-5 grid gap-5 md:grid-cols-2"><Field label="Shipper" value={form.shipperName} onChange={v=>update("shipperName",v)}/><Field label="Consignee" value={form.consigneeName} onChange={v=>update("consigneeName",v)}/><Field label="Shipper Address" value={form.shipperAddress} multiline onChange={v=>update("shipperAddress",v)}/><Field label="Consignee Address" value={form.consigneeAddress} multiline onChange={v=>update("consigneeAddress",v)}/><Field label="Notify Party" value={form.notifyPartyName} onChange={v=>update("notifyPartyName",v)}/><Field label="Notify Address" value={form.notifyPartyAddress} multiline onChange={v=>update("notifyPartyAddress",v)}/></div></section>
    <section className="rounded-xl border border-zinc-800 bg-zinc-950 p-6"><h2 className="text-lg font-semibold">Routing & Voyage</h2><div className="mt-5 grid gap-5 md:grid-cols-2"><Field label="Place of Receipt" value={form.placeOfReceipt} onChange={v=>update("placeOfReceipt",v)}/><Field label="Place of Delivery" value={form.placeOfDelivery} onChange={v=>update("placeOfDelivery",v)}/><Field label="Port of Loading" value={form.portOfLoading} onChange={v=>update("portOfLoading",v)}/><Field label="Port of Discharge" value={form.portOfDischarge} onChange={v=>update("portOfDischarge",v)}/><Field label="Vessel" value={form.vesselName} onChange={v=>update("vesselName",v)}/><Field label="Voyage" value={form.voyageNumber} onChange={v=>update("voyageNumber",v)}/><Field label="Issue Place" value={form.placeOfIssue} onChange={v=>update("placeOfIssue",v)}/></div></section>
    <section className="rounded-xl border border-zinc-800 bg-zinc-950 p-6"><h2 className="text-lg font-semibold">Container</h2><p className="mt-1 text-sm text-zinc-500">The B/L inherits the container assigned to the booking. Container reassignment must be performed on the booking.</p><div className="mt-5 rounded-lg border border-zinc-900 bg-black p-4">{booking?.container ? <><div className="font-mono font-semibold">{booking.container.containerNumber}</div><div className="mt-1 text-xs text-zinc-500">{booking.container.size} · {booking.container.type} · {booking.container.status}</div></> : <p className="text-sm text-zinc-600">No container is assigned to this booking.</p>}</div></section>
    <section className="rounded-xl border border-zinc-800 bg-zinc-950 p-6"><h2 className="text-lg font-semibold">Cargo</h2><div className="mt-5 grid gap-5 md:grid-cols-2"><Field label="Description" value={form.description} multiline onChange={v=>update("description",v)}/><Field label="Marks & Numbers" value={form.marksAndNumbers} multiline onChange={v=>update("marksAndNumbers",v)}/><Field label="Packages" value={form.totalPackages} type="number" onChange={v=>update("totalPackages",v)}/><Field label="Gross Weight" value={form.totalGrossWeight} type="number" onChange={v=>update("totalGrossWeight",v)}/><Field label="Measurement" value={form.totalMeasurement} type="number" onChange={v=>update("totalMeasurement",v)}/><Field label="Currency" value={form.currency} onChange={v=>update("currency",v.toUpperCase())}/><Field label="Declared Value" value={form.declaredValue} type="number" onChange={v=>update("declaredValue",v)}/><Field label="Freight Terms" value={form.freightTerms} onChange={v=>update("freightTerms",v)}/></div></section>
    <section className="rounded-xl border border-zinc-800 bg-zinc-950 p-6"><h2 className="text-lg font-semibold">Document Controls</h2><div className="mt-5 grid gap-5 md:grid-cols-2"><Field label="Number of Originals" value={form.numberOfOriginals} type="number" onChange={v=>update("numberOfOriginals",v)}/><Field label="Terms & Clauses" value={form.termsText} multiline onChange={v=>update("termsText",v)}/></div></section>
    <div className="flex justify-end gap-3"><button type="button" onClick={()=>router.push("/bills-of-lading")} className="rounded-lg border border-zinc-700 px-5 py-2.5 text-sm">Cancel</button><button disabled={saving||!booking} className="rounded-lg bg-white px-5 py-2.5 text-sm font-semibold text-black disabled:opacity-50">{saving?"Creating...":"Create Draft B/L"}</button></div>
  </form>;
}

function Field({label,value,onChange,multiline=false,type="text"}:{label:string;value:string|number|undefined;onChange:(v:string)=>void;multiline?:boolean;type?:string}){const c="mt-2 w-full rounded-lg border border-zinc-800 bg-zinc-950 px-3 py-2.5 text-sm text-white outline-none focus:border-zinc-500";return <label className="block"><span className="text-xs font-medium uppercase tracking-wide text-zinc-500">{label}</span>{multiline?<textarea rows={4} value={String(value??"")} onChange={e=>onChange(e.target.value)} className={c}/>:<input type={type} value={String(value??"")} onChange={e=>onChange(e.target.value)} className={c}/>}</label>}
